// <auto-generated />
namespace Helalzahbi_Trans.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addtbl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addtbl));
        
        string IMigrationMetadata.Id
        {
            get { return "201903151525575_addtbl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
